function E_ion = map_current_reversalPotential(current)

    parametres.HH_Model_AB_Parameters;
    % Make the struct map
    V_map = struct( ...
        'Na', V_Na, ...
        'K', V_K, ...
        'CaL', V_CaL, ...
        'AHP', V_AHP, ...
        'CaT', V_CaT, ...
        'H', V_H, ...
        'CAN', V_CAN, ...
        'Ks', V_Ks, ...
        'L', V_L ...
        );

    % Now, given a string like 'Na'
    E_ion = V_map.(current);                % V_Na

end
